using System;
using System.IO;
using System.Linq;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RevitMCPBridge.Helpers;

namespace RevitMCPBridge
{
    /// <summary>
    /// Imports vicinity_map.json (generated by generate_vicinity_map.py) as
    /// editable Revit detail lines and text notes in a new drafting view.
    /// </summary>
    public static class VicinityMapMethods
    {
        private static string OutputDir =>
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                         "BIM Monkey");

        [MCPMethod("createVicinityMapLines", Category = "Detail",
            Description = "Import vicinity_map.json as editable detail lines and text notes in a new drafting view. " +
                          "Run generate_vicinity_map.py via runScript first to produce the JSON.")]
        public static string CreateVicinityMapLines(UIApplication uiApp, JObject parameters)
        {
            try
            {
                var doc = uiApp.ActiveUIDocument.Document;

                var jsonPath   = parameters["jsonPath"]?.ToString()
                                 ?? Path.Combine(OutputDir, "vicinity_map.json");
                var viewName   = parameters["viewName"]?.ToString();
                var scaleDenom = parameters["scale"]?.Value<int>() ?? 1200;

                if (!File.Exists(jsonPath))
                    return ResponseBuilder.Error(
                        $"JSON not found: {jsonPath}. Run generate_vicinity_map.py via runScript first.").Build();

                var data    = JObject.Parse(File.ReadAllText(jsonPath));
                var lines   = (JArray)(data["lines"]  ?? new JArray());
                var labels  = (JArray)(data["labels"] ?? new JArray());
                var address = data["address"]?.ToString() ?? "";

                if (string.IsNullOrEmpty(viewName))
                    viewName = string.IsNullOrEmpty(address)
                        ? "VICINITY MAP *"
                        : $"VICINITY MAP - {address.ToUpper()} *";

                // Smallest available text note type
                var textType = new FilteredElementCollector(doc)
                    .OfClass(typeof(TextNoteType))
                    .Cast<TextNoteType>()
                    .OrderBy(t => t.get_Parameter(BuiltInParameter.TEXT_SIZE)?.AsDouble() ?? 999)
                    .FirstOrDefault();
                var textTypeId = textType?.Id ?? ElementId.InvalidElementId;

                int lineCount = 0, labelCount = 0;
                ElementId viewId;

                using (var trans = new Transaction(doc, "Create Vicinity Map Lines"))
                {
                    trans.Start();

                    var viewFamilyType = new FilteredElementCollector(doc)
                        .OfClass(typeof(ViewFamilyType))
                        .Cast<ViewFamilyType>()
                        .FirstOrDefault(t => t.ViewFamily == ViewFamily.Drafting);

                    if (viewFamilyType == null)
                        return ResponseBuilder.Error("No drafting view family type found").Build();

                    var view   = ViewDrafting.Create(doc, viewFamilyType.Id);
                    view.Name  = viewName;
                    view.Scale = scaleDenom;
                    viewId     = view.Id;

                    // Street lines
                    foreach (var seg in lines)
                    {
                        try
                        {
                            double x1 = seg["x1"]?.Value<double>() ?? 0;
                            double y1 = seg["y1"]?.Value<double>() ?? 0;
                            double x2 = seg["x2"]?.Value<double>() ?? 0;
                            double y2 = seg["y2"]?.Value<double>() ?? 0;
                            if (Math.Abs(x2 - x1) < 0.001 && Math.Abs(y2 - y1) < 0.001) continue;
                            doc.Create.NewDetailCurve(view, Line.CreateBound(new XYZ(x1, y1, 0), new XYZ(x2, y2, 0)));
                            lineCount++;
                        }
                        catch { }
                    }

                    // Street labels
                    if (textTypeId != ElementId.InvalidElementId)
                    {
                        foreach (var label in labels)
                        {
                            try
                            {
                                double lx  = label["x"]?.Value<double>() ?? 0;
                                double ly  = label["y"]?.Value<double>() ?? 0;
                                string txt = label["text"]?.ToString() ?? "";
                                if (string.IsNullOrEmpty(txt)) continue;
                                var opts = new TextNoteOptions(textTypeId)
                                    { HorizontalAlignment = HorizontalTextAlignment.Center };
                                TextNote.Create(doc, view.Id, new XYZ(lx, ly, 0), txt, opts);
                                labelCount++;
                            }
                            catch { }
                        }

                        // Site marker at origin
                        try
                        {
                            var opts = new TextNoteOptions(textTypeId)
                                { HorizontalAlignment = HorizontalTextAlignment.Center };
                            TextNote.Create(doc, view.Id, XYZ.Zero, "*", opts);
                        }
                        catch { }
                    }

                    trans.Commit();
                }

                return ResponseBuilder.Success()
                    .With("viewId",     (int)viewId.Value)
                    .With("viewName",   viewName)
                    .With("scale",      scaleDenom)
                    .With("lineCount",  lineCount)
                    .With("labelCount", labelCount)
                    .WithMessage($"Vicinity map created: {lineCount} lines, {labelCount} labels — all elements are editable in Revit.")
                    .Build();
            }
            catch (Exception ex)
            {
                return ResponseBuilder.FromException(ex).Build();
            }
        }
    }
}
