using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RevitMCPBridge.Helpers;
using Serilog;

namespace RevitMCPBridge
{
    /// <summary>
    /// Imports vicinity_map.json (generated by generate_vicinity_map.py) as
    /// editable Revit detail lines and text notes in a new drafting view.
    /// </summary>
    public static class VicinityMapMethods
    {
        private class DismissAllFailures : IFailuresPreprocessor
        {
            public FailureProcessingResult PreprocessFailures(FailuresAccessor a)
            {
                var msgs = a.GetFailureMessages();
                Log.Warning("VicinityMap PreprocessFailures called: {Count} messages", msgs.Count);
                foreach (var f in msgs)
                {
                    var sev = f.GetSeverity();
                    Log.Warning("VicinityMap failure: sev={Sev}, desc={Desc}", sev, f.GetDescriptionText());
                    if (sev == FailureSeverity.Warning)
                    {
                        a.DeleteWarning(f);
                    }
                    else if (f.HasResolutionOfType(FailureResolutionType.DetachElements))
                    {
                        // "Can't keep elements joined" — detach (unjoin) without deleting
                        f.SetCurrentResolutionType(FailureResolutionType.DetachElements);
                        a.ResolveFailure(f);
                    }
                    // Intentionally NOT using DeleteElements — that would remove the lines we just created
                }
                return FailureProcessingResult.ProceedWithCommit;
            }
        }

        private static string OutputDir =>
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                         "BIM Monkey");

        [MCPMethod("generateVicinityMapData", Category = "Detail",
            Description = "Run generate_vicinity_map.py to fetch OSM street data for an address and produce vicinity_map.json. " +
                          "Call createVicinityMapLines after this succeeds. Prefer this over runScript — args are passed correctly.")]
        public static string GenerateVicinityMapData(UIApplication uiApp, JObject parameters)
        {
            try
            {
                var address = parameters["address"]?.ToString();
                if (string.IsNullOrWhiteSpace(address))
                    return ResponseBuilder.Error("address is required").Build();

                var wrapperDir = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                    "BIM Monkey", "wrapper");
                var scriptPath = Path.Combine(wrapperDir, "generate_vicinity_map.py");

                if (!File.Exists(scriptPath))
                    return ResponseBuilder.Error($"Script not found: {scriptPath}. Reinstall BIM Monkey.").Build();

                var timeoutSec  = parameters["timeoutSeconds"]?.Value<int>() ?? 120;
                var pngFile     = parameters["pngFile"]?.ToString() ?? "vicinity_map.png";
                var distMeters  = parameters["distMeters"]?.Value<int>() ?? 0;

                var distArg = distMeters > 0 ? $" --dist {distMeters}" : "";

                var psi = new ProcessStartInfo
                {
                    FileName               = "python",
                    Arguments              = $"\"{scriptPath}\" \"{address}\" \"{pngFile}\"{distArg}",
                    UseShellExecute        = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError  = true,
                    CreateNoWindow         = true,
                    WorkingDirectory       = OutputDir,
                };

                Log.Information("generateVicinityMapData: running script for address={Address}", address);

                using (var proc = Process.Start(psi))
                {
                    var stdout  = proc.StandardOutput.ReadToEnd();
                    var stderr  = proc.StandardError.ReadToEnd();
                    bool done   = proc.WaitForExit(timeoutSec * 1000);

                    if (!done)
                    {
                        try { proc.Kill(); } catch { }
                        return ResponseBuilder.Error($"Script timed out after {timeoutSec}s").Build();
                    }
                    if (proc.ExitCode != 0)
                        return ResponseBuilder.Error($"Script failed (exit {proc.ExitCode}): {stderr.Trim()}").Build();

                    var jsonPath = Path.Combine(OutputDir, "vicinity_map.json");
                    Log.Information("generateVicinityMapData: complete, jsonPath={Path}", jsonPath);

                    return ResponseBuilder.Success()
                        .With("jsonPath", jsonPath)
                        .With("stdout",   stdout.Trim())
                        .WithMessage($"OSM data fetched. JSON ready at: {jsonPath}")
                        .Build();
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, "generateVicinityMapData: unhandled exception");
                return ResponseBuilder.FromException(ex).Build();
            }
        }

        [MCPMethod("createVicinityMapLines", Category = "Detail",
            Description = "Import vicinity_map.json as editable detail lines and text notes in a new drafting view. " +
                          "Run generate_vicinity_map.py via runScript first to produce the JSON.")]
        public static string CreateVicinityMapLines(UIApplication uiApp, JObject parameters)
        {
            try
            {
                var doc = uiApp.ActiveUIDocument.Document;
                Log.Information("createVicinityMapLines: start, doc={Doc}", doc?.Title ?? "null");

                var jsonPath = parameters["jsonPath"]?.ToString()
                              ?? Path.Combine(OutputDir, "vicinity_map.json");
                var viewName = parameters["viewName"]?.ToString();

                Log.Information("createVicinityMapLines: jsonPath={Path}", jsonPath);

                if (!File.Exists(jsonPath))
                {
                    Log.Warning("createVicinityMapLines: JSON not found at {Path}", jsonPath);
                    return ResponseBuilder.Error(
                        $"JSON not found: {jsonPath}. Run generate_vicinity_map.py via runScript first.").Build();
                }

                var data    = JObject.Parse(File.ReadAllText(jsonPath));
                var lines   = (JArray)(data["lines"]  ?? new JArray());
                var labels  = (JArray)(data["labels"] ?? new JArray());
                var address = data["address"]?.ToString() ?? "";

                Log.Information("createVicinityMapLines: JSON loaded — {Lines} lines, {Labels} labels, address={Address}",
                    lines.Count, labels.Count, address);

                if (string.IsNullOrEmpty(viewName))
                    viewName = string.IsNullOrEmpty(address)
                        ? "VICINITY MAP *"
                        : $"VICINITY MAP - {address.ToUpper()} *";

                // Auto-scale: snap to nearest standard Revit scale so view.Scale doesn't throw.
                // Map coordinates are geographic feet; compute scale to fit ~8" wide on paper.
                double radiusFeet    = data["radiusFeet"]?.Value<double>() ?? (900 * 3.28084);
                double mapWidthFeet  = radiusFeet * 2.0;
                double targetWidthFt = (parameters["targetPaperWidthInches"]?.Value<double>() ?? 8.0) / 12.0;
                double rawScale      = mapWidthFeet / targetWidthFt;
                // Snap to nearest standard architectural/engineering scale
                int[] standardScales = { 120, 240, 480, 600, 1200, 2400, 4800, 6000, 9600, 12000, 24000 };
                int autoScale = standardScales.OrderBy(s => Math.Abs(s - rawScale)).First();
                int scaleDenom = parameters["scale"]?.Value<int>() ?? autoScale;

                Log.Information("createVicinityMapLines: rawScale={Raw:F0}, snapped to {Scale}", rawScale, scaleDenom);

                // Smallest available text note type
                var textType = new FilteredElementCollector(doc)
                    .OfClass(typeof(TextNoteType))
                    .Cast<TextNoteType>()
                    .OrderBy(t => t.get_Parameter(BuiltInParameter.TEXT_SIZE)?.AsDouble() ?? 999)
                    .FirstOrDefault();
                var textTypeId = textType?.Id ?? ElementId.InvalidElementId;

                Log.Information("createVicinityMapLines: textTypeId={Id}", textTypeId?.Value.ToString() ?? "null");

                // Delete any existing vicinity map drafting views so re-runs don't accumulate duplicates.
                using (var txCleanup = new Transaction(doc, "Delete Stale Vicinity Map Views"))
                {
                    txCleanup.Start();
                    var stale = new FilteredElementCollector(doc)
                        .OfClass(typeof(ViewDrafting))
                        .Cast<ViewDrafting>()
                        .Where(v => v.Name.StartsWith("VICINITY MAP", StringComparison.OrdinalIgnoreCase))
                        .Select(v => v.Id)
                        .ToList();
                    int deleted = 0;
                    foreach (var id in stale)
                    {
                        try { doc.Delete(id); deleted++; }
                        catch { /* skip views that are on sheets */ }
                    }
                    if (deleted > 0)
                        Log.Information("createVicinityMapLines: deleted {N} stale vicinity map view(s)", deleted);
                    txCleanup.Commit();
                }

                int lineCount = 0, labelCount = 0;
                ElementId viewId;
                ViewDrafting persistedView;

                // If caller supplies an existing view ID, skip creation and target that view directly.
                int targetViewIdRaw = parameters["targetViewId"]?.Value<int>() ?? 0;
                if (targetViewIdRaw != 0)
                {
                    viewId = new ElementId(targetViewIdRaw);
                    persistedView = doc.GetElement(viewId) as ViewDrafting;
                    Log.Information("createVicinityMapLines: using existing viewId={Id}, found={Found}", targetViewIdRaw, persistedView != null);
                    if (persistedView == null)
                        return ResponseBuilder.Error($"No ViewDrafting found with id {targetViewIdRaw}").Build();
                    viewName = persistedView.Name;
                }
                else
                {
                // Transaction 1: create and name the view, commit before adding elements.
                using (var trans1 = new Transaction(doc, "Create Vicinity Map View"))
                {
                    var txStatus = trans1.Start();
                    Log.Information("createVicinityMapLines: tx1 status={Status}", txStatus);
                    if (txStatus != TransactionStatus.Started)
                        return ResponseBuilder.Error($"Transaction 1 failed to start: {txStatus}").Build();

                    var viewFamilyType = new FilteredElementCollector(doc)
                        .OfClass(typeof(ViewFamilyType))
                        .Cast<ViewFamilyType>()
                        .FirstOrDefault(t => t.ViewFamily == ViewFamily.Drafting);

                    if (viewFamilyType == null)
                    {
                        trans1.RollBack();
                        return ResponseBuilder.Error("No drafting view family type found").Build();
                    }

                    var view = ViewDrafting.Create(doc, viewFamilyType.Id);
                    Log.Information("createVicinityMapLines: ViewDrafting.Create id={Id}", view?.Id?.Value.ToString() ?? "null");

                    string safeName = viewName;
                    try { view.Name = safeName; }
                    catch
                    {
                        safeName = $"{viewName} {DateTime.Now:HHmmss}";
                        view.Name = safeName;
                    }
                    viewName = safeName;

                    try { view.Scale = scaleDenom; }
                    catch { scaleDenom = 9600; view.Scale = scaleDenom; }
                    Log.Information("createVicinityMapLines: view '{Name}' scale={Scale}", viewName, scaleDenom);

                    viewId = view.Id;
                    var c1 = trans1.Commit();
                    Log.Information("createVicinityMapLines: tx1.Commit()={Status}", c1);
                    if (c1 != TransactionStatus.Committed)
                    {
                        Log.Error("createVicinityMapLines: view creation rolled back");
                        return ResponseBuilder.Error("Failed to create drafting view (tx1 rolled back)").Build();
                    }
                    persistedView = doc.GetElement(viewId) as ViewDrafting;
                    Log.Information("createVicinityMapLines: persistedView={Status}", persistedView != null ? "OK" : "NULL");
                    if (persistedView == null)
                        return ResponseBuilder.Error("Failed to retrieve drafting view after tx1").Build();
                }
                } // end else (new view)

                // Commit every 25 segments in a separate transaction — Revit rolls back
                // single transactions containing more than ~40 NewDetailCurve calls.
                const int BATCH_SIZE = 25;
                int batchNum = 0;
                var pending = new System.Collections.Generic.List<(XYZ, XYZ)>();

                foreach (var seg in lines)
                {
                    try
                    {
                        double x1 = seg["x1"]?.Value<double>() ?? 0;
                        double y1 = seg["y1"]?.Value<double>() ?? 0;
                        double x2 = seg["x2"]?.Value<double>() ?? 0;
                        double y2 = seg["y2"]?.Value<double>() ?? 0;
                        if (!double.IsFinite(x1) || !double.IsFinite(y1) ||
                            !double.IsFinite(x2) || !double.IsFinite(y2)) continue;
                        var p1 = new XYZ(x1, y1, 0);
                        var p2 = new XYZ(x2, y2, 0);
                        if (p1.DistanceTo(p2) < 1e-6) continue;
                        pending.Add((p1, p2));
                    }
                    catch (Exception exSeg)
                    {
                        Log.Warning("createVicinityMapLines: skipping bad segment — {Err}", exSeg.Message);
                    }

                    if (pending.Count >= BATCH_SIZE)
                    {
                        batchNum++;
                        using (var txBatch = new Transaction(doc, $"Vicinity Map Lines {batchNum}"))
                        {
                            txBatch.Start();
                            int added = 0;
                            foreach (var (bp1, bp2) in pending)
                            {
                                try { doc.Create.NewDetailCurve(persistedView, Line.CreateBound(bp1, bp2)); added++; }
                                catch { }
                            }
                            var bs = txBatch.Commit();
                            if (bs != TransactionStatus.RolledBack) lineCount += added;
                            else Log.Warning("createVicinityMapLines: batch {N} rolled back", batchNum);
                        }
                        pending.Clear();
                    }
                }

                if (pending.Count > 0)
                {
                    batchNum++;
                    using (var txBatch = new Transaction(doc, $"Vicinity Map Lines {batchNum}"))
                    {
                        txBatch.Start();
                        int added = 0;
                        foreach (var (bp1, bp2) in pending)
                        {
                            try { doc.Create.NewDetailCurve(persistedView, Line.CreateBound(bp1, bp2)); added++; }
                            catch { }
                        }
                        var bs = txBatch.Commit();
                        if (bs != TransactionStatus.RolledBack) lineCount += added;
                        else Log.Warning("createVicinityMapLines: batch {N} rolled back", batchNum);
                    }
                    pending.Clear();
                }
                Log.Information("createVicinityMapLines: {Lines} lines drawn in {Batches} batches", lineCount, batchNum);

                using (var txMarker = new Transaction(doc, "Vicinity Map Site Marker"))
                {
                    txMarker.Start();
                    double arm = scaleDenom * (0.05 / 12.0);
                    double gap = arm * 0.05;
                    doc.Create.NewDetailCurve(persistedView, Line.CreateBound(new XYZ(-arm, 0, 0), new XYZ(-gap, 0, 0)));
                    doc.Create.NewDetailCurve(persistedView, Line.CreateBound(new XYZ(gap, 0, 0),  new XYZ(arm, 0, 0)));
                    doc.Create.NewDetailCurve(persistedView, Line.CreateBound(new XYZ(0, -arm, 0), new XYZ(0, -gap, 0)));
                    doc.Create.NewDetailCurve(persistedView, Line.CreateBound(new XYZ(0, gap, 0),  new XYZ(0, arm, 0)));
                    txMarker.Commit();
                }

                using (var txLabels = new Transaction(doc, "Vicinity Map Labels"))
                {
                    txLabels.Start();
                    foreach (var label in labels)
                    {
                        double x      = label["x"]?.Value<double>() ?? 0;
                        double y      = label["y"]?.Value<double>() ?? 0;
                        string text   = label["text"]?.ToString() ?? "";
                        double rotDeg = label["rotation"]?.Value<double>() ?? 0;
                        double rotRad = rotDeg * Math.PI / 180.0;
                        if (string.IsNullOrEmpty(text) || textTypeId == ElementId.InvalidElementId) continue;
                        var opts = new TextNoteOptions
                        {
                            TypeId = textTypeId,
                            HorizontalAlignment = HorizontalTextAlignment.Center,
                            Rotation = rotRad
                        };
                        try
                        {
                            TextNote.Create(doc, persistedView.Id, new XYZ(x, y, 0), text, opts);
                            labelCount++;
                        }
                        catch (Exception exLabel)
                        {
                            Log.Warning("createVicinityMapLines: skipping label '{T}' — {Err}", text, exLabel.Message);
                        }
                    }
                    var ls = txLabels.Commit();
                    if (ls == TransactionStatus.RolledBack)
                    {
                        labelCount = 0;
                        Log.Warning("createVicinityMapLines: labels tx rolled back");
                    }
                    Log.Information("createVicinityMapLines: {Labels} labels committed", labelCount);
                }

                if (lineCount == 0)
                {
                    try
                    {
                        using (var txDel = new Transaction(doc, "Delete Empty Vicinity Map View"))
                        {
                            txDel.Start();
                            doc.Delete(viewId);
                            txDel.Commit();
                            Log.Warning("createVicinityMapLines: deleted empty view {Id} after 0-line failure", viewId?.Value);
                        }
                    }
                    catch (Exception exDel)
                    {
                        Log.Warning(exDel, "createVicinityMapLines: could not delete empty view {Id}", viewId?.Value);
                    }
                    return ResponseBuilder.Error(
                        $"Vicinity map failed — 0 lines drawn across {batchNum} batches. " +
                        $"JSON had {lines.Count} segments. Check log for batch rollbacks.").Build();
                }

                using (var txCrop = new Transaction(doc, "Vicinity Map Crop Region"))
                {
                    txCrop.Start();
                    var bbox = new BoundingBoxXYZ();
                    bbox.Min = new XYZ(-radiusFeet, -radiusFeet, -1);
                    bbox.Max = new XYZ(radiusFeet,  radiusFeet,   1);
                    persistedView.CropBox       = bbox;
                    persistedView.CropBoxActive  = true;
                    persistedView.CropBoxVisible = false;
                    txCrop.Commit();
                    Log.Information("createVicinityMapLines: crop box set to ±{R} ft", Math.Round(radiusFeet));
                }

                Log.Information("createVicinityMapLines: complete — viewId={ViewId}, viewName={Name}, lines={Lines}, labels={Labels}",
                    viewId?.Value.ToString() ?? "null", viewName, lineCount, labelCount);

                return ResponseBuilder.Success()
                    .With("viewId",       (int)viewId.Value)
                    .With("viewName",     viewName)
                    .With("scale",        scaleDenom)
                    .With("mapWidthFeet", Math.Round(mapWidthFeet))
                    .With("lineCount",    lineCount)
                    .With("labelCount",   labelCount)
                    .WithMessage($"Vicinity map created: {lineCount} lines, {labelCount} labels at scale 1:{scaleDenom}.")
                    .Build();
            }
            catch (Exception ex)
            {
                Log.Error(ex, "createVicinityMapLines: unhandled exception");
                return ResponseBuilder.FromException(ex).Build();
            }
        }

    }
}
